//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace devamını_oku.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blogs
    {
        public int BlogID { get; set; }
        public string BlogTitle { get; set; }
        public string BlogImage { get; set; }
        public Nullable<System.DateTime> BlogDate { get; set; }
        public string BlogContent { get; set; }
    }
}
